### ISSUE TITLE
[JSS][Phulwari] Change in GMP form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss#25]
Ticket: https://avni.freshdesk.com/a/tickets/572

**Comment by garimadosar5** [comment]
QA Notes - 
- Height is showing for all the GMPs.

**Comment by sachsk** [comment]
it checks current age of child if it is in multiple of 2 (Months) then it shows the Height

**Comment by garimadosar5** [comment]
@sachsk Please deploy it on prod.
