### ISSUE TITLE
[JSS][Phulwari][Support] Data fix in case of double enrolment

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss#30]
ticket - https://avni.freshdesk.com/a/tickets/1090

- copy over the encounter data from the second enrolment to first enrolment and make the second enrolment null and void. 
- The list of children is attached in the ticket. (correction list Double Entry.xlsx)

**Comment by arjunk** [comment]
@garimadosar5 with the issue that has been highlighted on the ticket with this approach, i don't think the approach is final yet and so analysis is not complete.

**Comment by garimadosar5** [comment]
Closing this card as ticket is resolved.
