### ISSUE TITLE
[Phulwari] Report changes

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss#36]
Ref Doc - https://docs.google.com/document/d/1lGGvi0JJGJX813luiIN3-ulcp3MvYRO4LpvGBrWqbcg/edit?ts=60420c15
**Add New Filters**
- [x] Due Visits - https://reporting.avniproject.org/question/291
1. date range (On Due date), 
2. Catchment, 
3. Phulwari, 
4. Visit type,
5. Visit name
- [x] Faltering Children - https://reporting.avniproject.org/question/638
1. Phulwari
2. Grade
- [x] All Children - https://reporting.avniproject.org/question/1529
1. Enrolment date range filter
2. Exit date
3. Phulwari name
4. Catchment / Sector
- [x] New children enrolled in Phulwari in a month - https://reporting.avniproject.org/question/150
1. Catchment

**Add new Columns**
- [x] All Children - https://reporting.avniproject.org/question/1529
1. Date of last height, weight, WFA **Added date for last height & weight, wfa will have same date as last weight, so skipping that.**
2. Reason for exit
3. Cause of death with place & date
4. Birth order
5. Father name
6. Mother name
7. Father’s occupation
8. Mother’s occupation
9. Mother’s Education
10. Caste
11. Sub caste
12. Any owned land
13. Land area
14. Type of residence
15. Economic status
16. Any Property
17. Is children breastfeeding
18. Disabilities name

**Need to fix:** 
- [x] <Not used>Number of registration VS enrolments - https://reporting.avniproject.org/question/159 (Fix this report and remove not used tag)
1. Remove master catchment.
2. Check enrolment is more than reg. (one reason might be one child is enrolled twice.)
3. Remove master Catchments from all the reports. (if present in any report filter).
 - [x] List of children-weight not taken - https://reporting.avniproject.org/question/280
1. Column - "time since last weight taken" is not getting calculated properly.

**Name Change -** 
- [x] Name change - "Sync report" to "user wise consolidated data"
https://reporting.avniproject.org/question/181?start_date=2018-05-01

**Comment by nupoorkhandelwal** [comment]
Following are the 37 individuals who have 2 active enrolments. (And total 61 who have enrolled twice.)

44096,संजू,सिंह,2
44285,कविता ,देवी,2
44704,रेसमी,देवी,2
44771,सरस्वति,देवी,2
44843,सुवित्री,देवी,2
44851,ईश्वरी,देवी,2
45794,mamta,devi,2
45838,tejraj,singh,2
45907,nens,kumar,2
45920,preeti,devi,2
45921,kajal,devi,2
47531,काजल,देवी,2
57086,खविराज,सिंह,2
65686,प्रियांशु, सिंह,2
68487,आशिका,देवी,2
68490,कोमल,यादव,2
68491,राहुल,यदव,2
69429,रविन्द्र,सिंह,2
69976,ओमप्रकाश,सिंह,2
71037,भुनेश्वरी,देवी,2
82916,साक्षी,बैगा,2
83277,Sobhna ,Devi,2
83280,Bablu,Singh,2
99817,सतिस्ये,नायक,2
99819,भारती,देवी,2
100853,Anjni,देवी,2
106931,जैभान,सिंह,2
154559,लोक,सिंह,2
207352,हिमांशी,सिंह,2
317940,आनन्द,बैगा,2
334060,निक्या ,देवी,2
343915,दीपाली,देवी,2
343916,इसनेहा,देवी,2
344843,आशीष,बैगा,2
360203,उपेन्द्र,सिंह,2
360204,भरत,सिंह,2
370818,Test,Test,2

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Remove JSS master catchment from Catchment filter from all the reports.
https://reporting.avniproject.org/question/1529
https://reporting.avniproject.org/question/150
https://reporting.avniproject.org/question/638
https://reporting.avniproject.org/question/291
https://reporting.avniproject.org/question/280
https://reporting.avniproject.org/question/159
https://reporting.avniproject.org/question/162
https://reporting.avniproject.org/question/156
https://reporting.avniproject.org/question/457
https://reporting.avniproject.org/question/201
