### ISSUE TITLE
[Phulwari] App/form Changes

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss#37]
Ref Doc - https://docs.google.com/document/d/1lGGvi0JJGJX813luiIN3-ulcp3MvYRO4LpvGBrWqbcg/edit?ts=60420c15

**Phulwari Reg Form** -  **Done on JSS UAT**
- [x] Add question - "Day of month in Phulwari for Growth monitoring visit", (this question is currently asked for each child in child enrolment form) this question should not ask for each child. 

**Child Enrolment (Phulwari Program)** - 
- [ ] Remove the above question from child enrolment form. Cannot remove until Phulwari is live. And visit scheduling for Growth monitoring needs to be updated accordingly.

- [x] Add a new option No/None in the already existing question - "Disability",and migrate already existing enrolments where there is no disablity. Also, remove skip logic from this ques.

- [x] Change in Disability-related change (Reg form) [Migration required]
              - Add a question "Specify other"  if OTHER disability is selected.
-  [x] Change in "Any chronic illness”  question (reg form)
               - Add a question "Name of Disease" if Yes is selected for question "Any Chronic sickness".

**Offline report Setup** -    **Done on JSS UAT**
- [x] Offline Report “Registered but not enrolled”
Formula - All the children that are registered in the system but not enrolled in the Phulwari program.

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 Please test this change on staging!
