### ISSUE TITLE
[Phulwari] Setup Enrolment ID for each child.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss#39]
- [x] Format - [Sector ID][Phulwari ID][Running two digit number]

Format required - VIL-PHU-PH100

(Create IDs for all the sector and Phlwaris)
- [x] Migration of old data.

**Comment by garimadosar5** [comment]
**QA Notes-** 
- Enrolment ID changes on the previous button.
Steps - 
Fill enrolment form. Go to page enrolment id. Now press Previous. Again go to Next.
Now ID changes.

There are two children with same ID
1. Riya Gupta
2. Soman Sahay

**Comment by vindeolal** [comment]
Group and service are required for the above changes. Old rules do not support it yet. As we are already migrating JSS to a new type so this card can be picked up after the migration. Putting it on hold for now.

**Comment by garimadosar5** [comment]
QA Notes - 
- Already exited children's profile is crashing. for eg: Rohit Singh.
- Not related to this card but check if that needs to be changed - On edit of enrolment or any visit, new visits get scheduled.

**Comment by vindeolal** [comment]
- IDs were not assigned to exited subjects. Did that.
- This is known and enrolment should not be edited.
