### ISSUE TITLE
[Phulwari][Support] Remove Phulwari and villages

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss#41]
https://avni.freshdesk.com/a/tickets/1202

https://avni.freshdesk.com/a/tickets/1201

- [x] Delete  Salargondi village and its phulwari (Diwantola)
- [x] Delete MANJHETOLA Village and its PHULWARI (MANJHETOLA)
- [x] Rename Jarhi (Near Godantola) to Jairhi
- [x] Transfer individuals from Alwar sector --> Jarhi Village To  Ledhra Sector --> Jarhi village
- [x] Remove Jarhi Village from Alwar Sector.
- [ ] Remove Villages from annuppur which don't have phulwaris
- [x] Merge Chottibairagi and Badibairagi and create one village as Bairagi

Need to check if we do not have any data then we will directly remove or we need to do the migration of the cases.

**Comment by sachsk** [comment]
req. not clear
