### ISSUE TITLE
[Phulwari] New report - Monthly data of weight and Height

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss#42]
https://docs.google.com/document/d/1lGGvi0JJGJX813luiIN3-ulcp3MvYRO4LpvGBrWqbcg/edit?ts=60420c15

Report link --
https://reporting.avniproject.org/question/1627

- Monthly weight and height one in two months.
- Refer point 13 in doc

### Analysis
After discussing with the customer, the final requirements are here. 

Objective: Get height and weight as on a particular month for a child

### Columns
Date of birth
Age in months
Reg Date
Enrol Date
Exit Date
Catchment
Village
Phulwari
Gender
Time in months since enrolment
Age>=6 months
Enrolment number
Weight
Date of Weight
Height
Date of Height

### Filters
Month and Year

### Sorting
Sort by Phulwari first, individual first name next

### Performance
Must return within 15 seconds of firing the query

ticket - 
https://avni.freshdesk.com/a/tickets/1131

**Comment by garimadosar5** [comment]
QA Notes - 
- make all the date time to date format.
- Remove Master catchment.
-

**Comment by arjunk** [comment]
@vinayvenu Age in months column is missing
