### ISSUE TITLE
[Phulwari] Attendance report filter is not working for Harsh's account.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss#52]
In attendance related report, we have Month and year filter with dropdown but these are not working for harsh.
It is working for everyone's account within the team so we have got credentials of Harsh's account.

User ID: harshavardhan.shete18_dev@apu.edu.in
Password: 123456^AbcdE

**Comment by sachsk** [comment]
User are not able to see dropdown because of the JSS uat data access is not given to that user
