### ISSUE TITLE
[Phulwari][Support] Visit scheduling and visit migration

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss#62]
**To - dos -** 
• **JSS PHNI -** 
- [x] Keep the old logic and add one condition in the existing logic "When the month is December then add 0+1 and schedule next visit for January"
- [x] Do this change for both encounter and cancel encounter.
-  [x] There are some visits scheduled for 31 January. Migrate these visits so that January visit is schedule on the Phulwari day. (before migration check once all the visits are getting scheduled on Phulwari day for the respective Phulwari. Take the date from Phulwari registration form).

• **JSS CP -** 
- [x] Keep the old logic and add one condition in the existing logic "When the month is December then add 0+1 and schedule next visit for January".
- [x] Do this change for both encounter and cancel encounter.
-  [x] There are some visits scheduled for 31 January. Migrate these visits so that January visit is schedule on the Phulwari day. (before migration check once all the visits are getting scheduled on Phulwari day for the respective Phulwari. Take the date from Phulwari registration form).

• **JSS Singrauli -**
- [x] Keep the old logic and add one condition in the existing logic "When the month is December then add 0+1 and schedule next visit for January".
- [x] Do this change for both encounter and cancel encounter.
-  [x] There is no current visit scheduled for Jan 31 so migration not needed for this org

**Comment by nupoorkhandelwal** [comment]
Fixed visit scheduling on UAT organisations-

- [ ] JSS UAT - Visit on complete & on cancel

- [ ] JSSCP UAT - Visit on complete & on cancel

- [ ] JSS Singrauli - Visit on complete & on cancel

**Comment by nupoorkhandelwal** [comment]
Moved rules to prod. Please test and move the card to ready, we need to run migrations once users have synced from both the orgs.
