### ISSUE TITLE
[JSS Phulwari] Migrate Grade change reports to ETL - Card 1

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jss#85]
Earlier, JSS Phulwari reports on metabase were working fine but some how the performance has gone down and now the client is unable to access them.

So to unblock client, following set of reports need to picked up on priority -

- [x] Grade change
- [x] Grade change linelist
- [x] Grade change linelist weight not taken

**Make sure all filters and drill down (wherever appliocable ) are working and nothing new breaks during this ETL migration**

**Comment by nupoorkhandelwal** [comment]
@vedfordev i updated the aggregate report to count cancel encounters as well - https://reporting.avniproject.org/question/2909-grade-change?year=2023&month=2

Please update the corresponding linelist as well.

**Comment by Gojo-Taqi** [comment]
@nupoorkhandelwal I have made the changes on linelist as well.
Moving the card to code review ready.

**Comment by Gojo-Taqi** [comment]
Have made the changes in the other report as well.

**Comment by nupoorkhandelwal** [comment]
@Gojo-Taqi Compare the CTE for Weight not taken, there is a huge difference between both the numbers.

**Comment by Gojo-Taqi** [comment]
All the indicators are giving wrong values when compared to the linelist.
This card will take more time, moving the card back to ETL ready as there is an urgent ticket I need to take a look at.

**Comment by Dinesh2019** [comment]
- [x] Can we have the catchment filter added for all the grade change
- [x] Need to connect with taqi to check for count mismatch

**Comment by Dinesh2019** [comment]
- [ ] Need to check the count with taqi
