### ISSUE TITLE
[JSS Phulwari] Migrate reports to ETL - Card 2

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jss#86]
Earlier, JSS Phulwari reports on metabase were working fine but some how the performance has gone down and now the client is unable to access them.

So to unblock client, following set of reports need to picked up on priority -

- [x] Phulwariwise list of children absent for more than 3 days
- [x] Phulwariwise Monthly Attendance Report
- [x] Population Standard
- [x] Weight For Age Grade-Phulwari Children
- [x] Due Visits

**Make sure all filters and drill down (wherever appliocable ) are working and nothing new breaks during this ETL migration**

**Comment by Dinesh2019** [comment]
Can you tell me the drill down where it is applied
- [x] Phulwariwise list of children absent for more than 3 days after applying filter getting this error 

<img width="1275" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDdyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--075138bc25f578e81996dec83cdc3ed9a61071c7/image.png" alt="image.png" />

- [x] Phulwariwise Monthly Attendance Report - can we have the dropdown 

<img width="1264" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUhyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f9dd27747101951ef809711b9e02c859ca42573/image.png" alt="image.png" />

- [x] Weight For Age Grade-Phulwari Children

<img width="1256" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUxyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c0a880dfaf8968e2d65e7745e201307afefdbd2/image.png" alt="image.png" />

- [x] Due Visits is missing

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 The exiting Due visits report is itself moved to ETL, so there is no old report to test, it was giving errors.

And there is no drill down in any of these reports

**Comment by Dinesh2019** [comment]
- [x] Weight For Age Grade-Phulwari Children - can we have the dropdown

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHZyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b15eb95b937d9316f230633736d9edd7ddd9f2dc/Screenshot%202024-01-23%20at%201.49.47%E2%80%AFPM.png" alt="Screenshot 2024-01-23 at 1.49.47 PM.png" />
