### ISSUE TITLE
[JSS Phulwari] Migrate remaining reports to ETL - card 3

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jss#87]
Earlier, JSS Phulwari reports on metabase were working fine but some how the performance has gone down and now the client is unable to access them.
- [x] **Monthly data of weight and Height**
- [x] **New children enrolled in Phulwari in a month**
- [ ] All children with first and last measurements for specific dates
- [ ] Average Numbers for Phulwari
- [ ] Faltering Children
- [ ] Children Moved to Lower WFA grade
- [ ] Children Moved to Upper WFA grade
- [ ] Line list of Children- weight not taken
- [ ] New children enrolled in Phulwari in a month
- [ ] Number of registration VS enrolments
- [ ] Phulwari child weight gain (Enrolled Children)
- [ ] Test - Average weight gain over time
- [ ] User wise consolidated data

**Make sure all filters and drill down (wherever appliocable ) are working and nothing new breaks during this ETL migration**

**Comment by AnjaliBhagabati** [comment]
@BEULAHEVANJALIN you can start working on the first two reports:
 1. Monthly data of weight and Height
 2. New children enrolled in Phulwari in a month
 The other reports in this card are not marked as frequently used by the client. I will have to check with the client if they need these other reports or we can mark it as not required and remove it.
Reference link: https://docs.google.com/spreadsheets/d/1LZ7bXHO6DoWmoDbV3ENMNWaA0FFVUG0Ku1EaS9CiW_g/edit#gid=648644390

**Comment by BEULAHEVANJALIN** [comment]
Newly created reports can be found at https://reporting.avniproject.org/collection/568-jss-phulwari-etl

**Comment by Dinesh2019** [comment]
@AnjaliBhagabati @BEULAHEVANJALIN need the old report link to check the logic is updated is right or wrong blocked for this card

**Comment by AnjaliBhagabati** [comment]
@Dinesh2019 here are the old report links
 

- [ ] **All children with first and last measurements for specific dates:** https://reporting.avniproject.org/question/1529-all-children-with-first-and-last-measurements-for-specific-dates
- [ ] **New children enrolled in Phulwari in a month:** https://reporting.avniproject.org/question/2940-new-children-enrolled-in-phulwari-in-a-month
- [ ] Monthly data of weight and Height: https://reporting.avniproject.org/question/1627-monthly-data-of-weight-and-height?month=1&year=2021

**Comment by Dinesh2019** [comment]
- [ ] @AnjaliBhagabati New children enrolled in Phulwari in a month: https://reporting.avniproject.org/question/2940-new-children-enrolled-in-phulwari-in-a-month this is pointing to new report url

**Comment by AnjaliBhagabati** [comment]
- [ ] @Dinesh2019 can you please check with this https://reporting.avniproject.org/question/150-new-children-enrolled-in-phulwari-in-a-month

**Comment by Dinesh2019** [comment]
For new children enrolled in Phulwari in a month, we have an amount mismatch between old report and new report 

New count : 3459
Old count :  3315
