### ISSUE TITLE
[JSS Phulwari] Migrate an important report to ETL

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jss#88]
## Existing report 
 https://reporting.avniproject.org/question/1529-all-children-with-first-and-last-measurements-for-specific-dates

## Tech tasks

- [x] Update the report to use ETL tables
- [x] Make sure filters are not broken

**Comment by BEULAHEVANJALIN** [comment]
https://reporting.avniproject.org/question/2986-all-children-with-first-and-last-measurements-for-specific-dates

**Comment by Dinesh2019** [comment]
- [ ] We have a count mismatch between the old and new report 

New report: 3873
Old report : 3884
